*: support backup/restore with  NFS #148
radondb/radondb-mysql-kubernetes pull request #232
Opened 2021-09-24 02:14 UTC by acekingke

### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes #148 

### What this PR does?

Summary:
1. create nfs resouce and nfs service
2. support backup to nfs and restore from nfs
### Special notes for your reviewer?

2021-09-24 06:13 UTC, runkecheng commented on config/samples/nfs_server.yaml
> +    role: nfs-server
Blank line at the end.

2022-04-14 07:36 UTC, andyli029 commented
staticcheck Failed.

2022-04-14 08:44 UTC, andyli029 commented on sidecar/init.go
> +
Delete the space line.

2022-04-14 08:47 UTC, andyli029 commented on api/v1alpha1/backup_types.go
> +	// Represents the name of backup to NFS
Is `IP of NFS server`?

2022-04-14 08:49 UTC, andyli029 commented on backup/syncer/job.go
> +
Delete it.

2022-04-14 08:52 UTC, andyli029 commented on backup/syncer/job.go
> +			fmt.Sprintf("mkdir -p /backup/%s;curl --user $BACKUP_USER:$BACKUP_PASSWORD %s/download|xbstream -x -C /backup/%s; exit ${PIPESTATUS[0]}",
->
```
			fmt.Sprintf("mkdir -p /backup/%s; " +
				"curl --user $BACKUP_USER:$BACKUP_PASSWORD %s/download|xbstream -x -C /backup/%s; " +
				"exit ${PIPESTATUS[0]}",
				backupToDir, 
				s.backup.GetBackupURL(s.backup.Spec.ClusterName, s.backup.Spec.HostName), backupToDir),
```

2022-04-14 08:58 UTC, andyli029 reviewed
Add subdir `back-nfs` in the samples about and mv related file into it.

2022-04-15 04:13 UTC, runkecheng requested changes

2022-04-15 04:13 UTC, runkecheng commented on config/samples/nfs_rc.yaml
> +            claimName: backup-pv-volume
claimName should be pvc name: backup-pv-claim

2022-04-15 04:13 UTC, runkecheng commented on config/samples/pv-volume.yaml
> +apiVersion: v1
1. add sc
2. support source is LocalVolume?

2022-04-15 06:52 UTC, andyli029 commented on docs/deploy_backup_restore_nfs.md
> +Or use local storage pvc, see `config/sample/pv-claim.yalm`
yalm
->
yaml?

2022-04-15 07:01 UTC, runkecheng requested changes
The name of the backup folder cannot distinguish the backup of multiple clusters, Change the name such as `<cluster_name>_202241564422`.
`
sh-4.2# ls exports/
backup_202241564422  index.html
sh-4.2# ls exports/backup_202241564422/
backup-my.cnf   ibdata1  performance_schema  sys                     xtrabackup_checkpoints  xtrabackup_logfile
ib_buffer_pool  mysql    radondb             xtrabackup_binlog_info  xtrabackup_info
`

2022-04-15 08:17 UTC, acekingke commented
https://github.com/radondb/radondb-mysql-kubernetes/pull/232#discussion_r851094310 
cannot use GetNameForResource, it is `MysqlCluster` method, can not call in sidecar

2022-04-15 08:22 UTC, runkecheng commented on config/samples/pv-volume.yaml
> +          - node2
nodeAffinity is not necessary， if haven't node2, PV will not be created.

2022-04-15 09:12 UTC, runkecheng commented on docs/deploy_backup_restore_nfs.md
> +kubectl apply -f config/samples/mysql_v1alpha1_backup.yaml
Notice: backup cr and mysqlcluster cr must be in the same namespace.

2022-04-18 01:47 UTC, acekingke commented
> The name of the backup folder cannot distinguish the backup of multiple clusters, Change the name such as <cluster_name>_202241564422.



it has been modified

2022-04-18 02:15 UTC, runkecheng commented on config/samples/mysql_v1alpha1_backup.yaml
>    image: radondb/mysql-sidecar:latest
mysql57-sidecar:v2.2.0

2022-04-18 10:22 UTC, runkecheng approved these changes

2022-04-18 10:24 UTC, andyli029 approved these changes
Merge first, optimize further.

2022-04-18 10:24 UTC, merged