sidecar: change restore.sh to go codes #292
radondb/radondb-mysql-kubernetes pull request #293
Opened 2021-11-09 04:22 UTC by acekingke

### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes #292 

### What this PR does?

Summary:

### Special notes for your reviewer?

2021-11-09 07:10 UTC, runkecheng requested changes

2021-11-09 07:10 UTC, runkecheng commented on sidecar/config.go
> +	//check has directory, and create it.
fix note. like // Check has directory, and create it.

2021-11-12 03:45 UTC, runkecheng requested changes

2021-11-12 03:45 UTC, runkecheng commented on sidecar/config.go
> +			return fmt.Errorf("create data directory fail : %s", err)
`failed to xxx` is better?

2021-11-12 03:45 UTC, runkecheng commented on sidecar/config.go
> +		return fmt.Errorf("create backup directory fail : %s", err)
same as the last.

2021-11-15 08:50 UTC, runkecheng approved these changes

2021-11-15 08:51 UTC, runkecheng commented
lgtm

2021-11-22 08:37 UTC, andyli029 commented on sidecar/config.go
> -rm -rf /root/backup
The step is ignored.

2021-11-23 02:34 UTC, andyli029 reviewed
LGTM.

2021-11-23 02:34 UTC, merged