mysqlcluster, utils: The time zone of the container and the mysql are…
radondb/radondb-mysql-kubernetes pull request #329
Opened 2021-12-08 03:10 UTC by acekingke

… inconsistent. #325

### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #325

### What this PR does?

Summary:

### Special notes for your reviewer?

2021-12-08 03:25 UTC, runkecheng requested changes

2021-12-08 03:25 UTC, runkecheng commented on utils/constants.go
> +	// volume mount host path for time zone
fix comment like line 116.

2021-12-08 06:20 UTC, runkecheng approved these changes
lgtm

2021-12-09 03:42 UTC, andyli029 reviewed
LGTM.

2021-12-09 03:42 UTC, merged