docs/rancher *: Add docs about deploy radondb mysql on rancher #338
radondb/radondb-mysql-kubernetes pull request #339
Opened 2021-12-20 10:15 UTC by molliezhang

### What type of PR is this?

/documentation
/enhancement

### Which issue(s) this PR fixes?

Fixes #338 

### What this PR does?

Summary:

### Special notes for your reviewer?
@andyli029 @runkecheng @KID-G @qianfen2021 @acekingke

2021-12-20 10:20 UTC, runkecheng commented on docs/rancher/deploy_radondb-mysql_operator_on_rancher.md
> +### 同 NameSpace 访问
Here can be simplify.

2021-12-23 09:48 UTC, runkecheng requested changes

2021-12-23 09:48 UTC, runkecheng commented on docs/rancher/deploy_radondb-mysql_operator_on_rancher.md
> +2. 在 Rancher 集群管理页面，点击右上角 YAML 导入图标。自啊弹出的窗口中，导入修改后的 YAML 文件。
自动弹出

2021-12-23 09:48 UTC, runkecheng commented on docs/rancher/deploy_radondb-mysql_operator_on_rancher.md
> +以下主要演示客户端与数据库在同一 Rancher 集群内场景，访问 RadonDB MySQL 的方式。
以下主要演示在...的场景下

2021-12-23 09:48 UTC, runkecheng commented on docs/rancher/deploy_radondb-mysql_operator_on_rancher.md
> +以下示例用户名为 `radondb_usr`，cluster IP 为 `10.10.128.136` ，连接示例如下：
可以用主/从服务的cluster IP来举例

2021-12-24 03:21 UTC, runkecheng approved these changes
lgtm

2021-12-24 07:50 UTC, runkecheng approved these changes

2021-12-28 02:38 UTC, andyli029 commented
LGTM.

2021-12-28 02:38 UTC, merged