docs/kubernetes *: Update the description about access radondb mysql #340
radondb/radondb-mysql-kubernetes pull request #341
Opened 2021-12-21 11:00 UTC by molliezhang

### What type of PR is this?

/documentation
/enhancement

### Which issue(s) this PR fixes?

Fixes #340 

### What this PR does?

Summary:

### Special notes for your reviewer?
@acekingke @andyli029 @runkecheng @qianfen2021 @KID-G

2021-12-22 02:06 UTC, runkecheng requested changes

2021-12-22 02:06 UTC, runkecheng commented on docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +- 在 Kubernetes 集群内，支持选择使用 `service_name` 或者 `service_IP` 方式访问 RadonDB MySQL。
service_IP -> ClusterIP，see [k8s service](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)

2021-12-22 02:06 UTC, runkecheng commented on docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +    $ mysql -h <leader_service_name> -u <user_name> -p
Add ns like `sample-leader.default`

2021-12-22 02:35 UTC, molliezhang commented on docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +    $ mysql -h <leader_service_name> -u <user_name> -p
ok

2021-12-22 02:35 UTC, molliezhang commented on docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +- 在 Kubernetes 集群内，支持选择使用 `service_name` 或者 `service_IP` 方式访问 RadonDB MySQL。
ok

2021-12-22 02:36 UTC, molliezhang commented on docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +- 当客户端的与数据库部署在不同 Kubernetes 集群，请参考 [Kubernetes 访问集群中的应用程序](https://kubernetes.io/zh/docs/tasks/access-application-cluster/)，配置端口转发、负载均衡等连接方式。
ok

2021-12-24 03:23 UTC, runkecheng approved these changes
lgtm

2021-12-27 03:04 UTC, andyli029 commented
LGTM.

2021-12-27 03:04 UTC, merged