Ginkgo v2
radondb/radondb-mysql-kubernetes pull request #360
Opened 2022-01-11 03:29 UTC by runkecheng

### What type of PR is this?

/enhancement

### Which issue(s) this PR fixes?

Fixes #344
Fixes #358

### What this PR does?

Summary:

- Upgrade Ginkgo to V2 version, replace the API

- Each suite`s logs is stored in a separate folder and outputs the test overview.

- POD logs of different use cases are output to different files

- Wait for the NS to remove and then exit after completing the test

- Configure unified management

- Add the test case of the cluster-related API and cluster scale out/in

- Add a label for each level of the use case

- Example of adding screening cases in documentation

### Special notes for your reviewer?

2022-01-11 07:30 UTC, runkecheng commented
https://github.com/onsi/ginkgo/issues/874

2022-01-11 09:44 UTC, andyli029 commented on test/e2e/README.md
> +- Running all cases
Add ginkgo version

2022-01-11 11:04 UTC, andyli029 commented on test/e2e/framework/test_context.go
> +	ReportDir = "e2e_logs"
ReportDir
->
ReportDirPrefix

2022-01-17 09:47 UTC, acekingke commented on test/e2e/e2e_test.go
> +		os.MkdirAll(fmt.Sprintf("%s_%d", framework.TestContext.ReportDirPrefix, GinkgoRandomSeed()), 0777)
dir maybe do not random， use date time maybe reasonable.

2022-01-17 09:47 UTC, acekingke commented on test/e2e/e2e_test.go
> +		f, err := os.OpenFile(path.Join(fmt.Sprintf("%s_%d", framework.TestContext.ReportDirPrefix, GinkgoRandomSeed()), "overview.txt"), os.O_RDWR|os.O_CREATE, 0644)
the same to above

2022-02-07 09:35 UTC, andyli029 commented on test/e2e/README.md
> +> The Ginkgo version of the following examples is V2.
Add reference about ginkgo.

2022-02-07 09:38 UTC, andyli029 requested changes
Ping

2022-02-08 08:00 UTC, andyli029 approved these changes

2022-02-08 08:00 UTC, merged