mysqlcluster: Debug Mode for Pod #375
radondb/radondb-mysql-kubernetes pull request #383
Opened 2022-02-10 12:51 UTC by acekingke

### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes #375 

### What this PR does?

Summary:
add the debug mode, make container never recreate when mysqld crashed
### Special notes for your reviewer?

2022-02-15 07:40 UTC, andyli029 commented on docs/en-us/DebugMode.md
> +it make pod sample-mysql-0's mysql container will never restart when mysqld is crashed.
Add cmd about cancel Debug

2022-02-22 03:16 UTC, andyli029 commented
Ping @runkecheng

2022-02-22 07:10 UTC, runkecheng requested changes

2022-02-28 03:01 UTC, runkecheng approved these changes
lgtm

2022-02-28 03:06 UTC, runkecheng commented
I am not sure that there will be other risks in the container if run the main logic not in the first process.

2022-03-03 10:29 UTC, andyli029 approved these changes

2022-03-03 10:29 UTC, merged