mysqlcluster: Support the more elegant way to rebuild node. #385
radondb/radondb-mysql-kubernetes pull request #389
Opened 2022-02-24 08:39 UTC by acekingke

### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes #385 

### What this PR does?

Summary:
1. track lable `rebuild` and rebuild the pod
### Special notes for your reviewer?

2022-02-28 03:00 UTC, runkecheng requested changes

2022-02-28 03:00 UTC, runkecheng commented on mysqlcluster/syncer/status.go
> +		if pod.ObjectMeta.Labels["rebuild"] == "true" {
Define the content of the label into a global variable

2022-02-28 03:00 UTC, runkecheng commented on mysqlcluster/syncer/status.go
> +	if err := s.cli.Delete(ctx, pod); err != nil {
Set unhealthy and update before delete pod

2022-03-10 07:09 UTC, runkecheng approved these changes

2022-03-14 03:25 UTC, andyli029 approved these changes
1. Add command
2. Fix the commit log

2022-03-14 05:53 UTC, runkecheng approved these changes

2022-03-17 08:39 UTC, andyli029 reviewed
LGTM.

2022-03-17 08:39 UTC, merged