docs: Add offline deployment document. #396
radondb/radondb-mysql-kubernetes pull request #399
Opened 2022-03-07 07:25 UTC by runkecheng

### What type of PR is this?

doc

### Which issue(s) this PR fixes?

Fixes #396 

### What this PR does?

Summary:

### Special notes for your reviewer?

The resources needed to deploy have been uploaded to Release.

Need to verify that the process can go through.

2022-03-09 02:43 UTC, andyli029 requested changes
deployment-resources.tar.gz->?
v2.1.2-resources->?

@molliezhang  @runkecheng

2022-03-09 02:44 UTC, andyli029 commented on docs/zh-cn/deploy_radondb-mysql_operator_on_k8s_offline.md
> +## 导入镜像（需要在每个运行数据库的 worker 上执行）
cd dir

2022-03-14 02:50 UTC, molliezhang reviewed
LGTM

2022-03-14 06:35 UTC, qianfen2021 commented
LGTM

2022-03-16 02:36 UTC, andyli029 approved these changes
LGTM.

2022-03-16 02:36 UTC, merged