Lowcase table name
radondb/radondb-mysql-kubernetes pull request #481
Opened 2022-05-12 01:05 UTC by acekingke

### What type of PR is this?

/bug
### Which issue(s) this PR fixes?

Fixes #477

### What this PR does?

Summary:
Use webhook to forbidden the mysqlconf's modifies
### Special notes for your reviewer?

2022-05-12 01:54 UTC, runkecheng commented on docs/en-us/deploy_radondb-mysql_operator_on_k8s.md
> +kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
After installing the Certmanager, the user should also execute the `kubectl kusomize config`

2022-05-12 01:56 UTC, runkecheng commented on docs/en-us/deploy_radondb-mysql_operator_on_k8s.md
> +kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
We can refer to this approach: https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/cert-manager-certs.yaml

2022-05-24 02:32 UTC, runkecheng commented
need rebase

2022-05-25 06:43 UTC, runkecheng requested changes

2022-05-25 06:43 UTC, runkecheng commented on api/v1alpha1/mysqlcluster_webhook.go
> +		r.Spec.MysqlVersion != "8.0" {
mysql57 no such limit.
```
r.Spec.MysqlVersion == "8.0" && oldmyconf["lower_case_table_names"] != newmyconf["lower_case_table_names"] 
```

2022-05-25 06:43 UTC, runkecheng commented on api/v1alpha1/mysqlcluster_webhook.go
> +		return apierrors.NewForbidden(schema.GroupResource{}, "", fmt.Errorf("lower_case_table_names cannot be changed"))
```
fmt.Errorf("lower_case_table_names cannot be changed in MySQL8.0+"
```

2022-05-25 06:43 UTC, runkecheng commented on api/v1alpha1/mysqlcluster_webhook.go
> +		return apierrors.NewForbidden(schema.GroupResource{}, "", fmt.Errorf("lower_case_table_names cannot be changed"))
```
fmt.Errorf("lower_case_table_names cannot be changed in MySQL8.0+"
```

2022-05-25 07:49 UTC, runkecheng approved these changes

2022-05-25 10:15 UTC, andyli029 approved these changes
lgtm.

2022-05-25 10:15 UTC, merged