api,backup: add printcolumn for Success #668
radondb/radondb-mysql-kubernetes pull request #670
Opened 2022-08-24 06:49 UTC by acekingke

### What type of PR is this?

/enhancement
### Which issue(s) this PR fixes?

Fixes #668

### What this PR does?

Summary:
1. add column for backup which indicate Success.
### Special notes for your reviewer?

2022-08-24 07:49 UTC, zhl003 approved these changes
LGTM

2022-08-26 07:12 UTC, runkecheng requested changes
make update-crd

2022-08-26 07:28 UTC, acekingke commented
> make update-crd

it fixes

2022-08-26 07:33 UTC, runkecheng approved these changes

2022-08-26 07:38 UTC, merged