feat(e2e): add podchaos api and test cases
radondb/radondb-mysql-kubernetes pull request #697
Opened 2022-09-14 02:01 UTC by chengbaitai

### What type of PR is this?

/enhancement

### Which issue(s) this PR fixes?

Fixes #682 

### What this PR does?

Summary:
Chaos Mesh is a cloud native Chaos Engineering platform that orchestrates chaos on Kubernetes [`Chaos documents.`](https://chaos-mesh.org/zh/docs/).Chaos mesh use CRD defnine many types of fault and provide detailed of parameter description.So wei can mainly focus on life cycle of CRD instead of focus on basic implements of specific faults.
The details of this implements as follows:

- introduce chaos mesh api into e2e
- programming API according to definition of faults
- programming test case

- [x] podkill
- [x] containerkill
- [ ] podfailure

### Special notes for your reviewer?

2022-09-15 00:56 UTC, runkecheng commented
ci检查未通过，提交代码前执行：
```
go fmt ./...
go vet ./...
```

2022-09-15 01:00 UTC, runkecheng commented
import 规范参考 https://github.com/radondb/radondb-mysql-kubernetes/pull/693#discussion_r970212681

2022-09-20 06:27 UTC, runkecheng commented
建议补充成功注入后的资源信息，例如mysql节点，podchaos。

2022-09-20 06:27 UTC, runkecheng requested changes

2022-09-20 06:27 UTC, runkecheng commented on test/e2e/chaos/podChaos.go
> +func killLeader(f *framework.Framework) {
其他故障也需要补充

2022-09-20 07:05 UTC, runkecheng commented on test/e2e/framework/chaos.go
> +func (f *Framework) KillContainers(option *PodChaosOptions) {
缺少containers参数输入
```
Spec.containerNames: Invalid value: []string(nil): the name of container is required on container-kill action: invalid value
```

2022-09-20 07:12 UTC, runkecheng commented on test/e2e/framework/chaos.go
> +func (f *Framework) waitChaosInjected(chaosName string, timeout time.Duration) {
判断注入的过程应该有日志输出

2022-09-20 07:15 UTC, runkecheng commented on test/e2e/framework/chaos.go
> +package framework
补充清理测试环境（测试时创建的chaos）的api

2022-09-22 08:29 UTC, acekingke approved these changes
LGTM

2022-09-22 09:39 UTC, zhl003 approved these changes
LGTM

2022-09-27 02:11 UTC, merged