docs: Add steps to configure the service network #85
radondb/radondb-mysql-kubernetes pull request #86
Opened 2021-04-28 03:53 UTC by runkecheng

- Replace the picture in the document
- add steps to configure the service network 
   - NodePort
   - LoadBalancer

2021-04-28 04:04 UTC, andyli029 reviewed
Fix the commit log

2021-04-28 05:46 UTC, molliezhang commented
LGTM

2021-04-28 06:53 UTC, runkecheng commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +在**项目管理**管理中心，选择 **应用负载 > 工作负载**，并选择**有状态副本集**页签，可查看到 release 名为 `demo` 的副本集，则 radondb-mysql 集群已成功部署。
radondb-mysql -> RadonDB MySQL

2021-04-28 08:44 UTC, zhyass requested changes

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +  点击 **部署新应用**，在 **来自应用模板**窗口中选择 `RadonDB MySQL`。
From the [picture](https://github.com/runkecheng/radondb-mysql-kubernetes/blob/rename_keyword/docs/KubeSphere/png/%E9%83%A8%E7%BD%B2%E6%96%B0%E5%BA%94%E7%94%A8.png), the application name is `radondb-mysql`

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +在**项目管理**管理中心，选择 **应用负载 > 工作负载**，并选择**有状态副本集**页签，可查看到 release 名为 `demo` 的副本集，则 RadonDB MySQL 集群已成功部署。
The name of the statefulset is `demo-radondb-mysql`
https://github.com/runkecheng/radondb-mysql-kubernetes/blob/rename_keyword/docs/KubeSphere/png/%E6%8E%A7%E5%88%B6%E5%8F%B0%E9%83%A8%E7%BD%B2%E6%88%90%E5%8A%9F.png

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +当客户端和 RadonDB MySQL 集群在同一个项目中时，可使用 leader/follower 代替具体的 ip 和端口。
Maybe you can display the `服务` before `连接数据库`, and briefly describe the meaning of each service. 
This is not `leader/follower`, but the `leader service` and `follower service`.

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +- 连接主节点。
underline  read write

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +- 连接从节点。
underline read only

2021-04-28 08:44 UTC, zhyass commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +3. 获取外网访问 IP 和端口。
Only applicable to scenarios where kubesphere is created in the qingcloud console. 
In fact, we do not recommend port forwarding on the public network.  You can `在同一 VPC 下主机来访问，或者通过青云 VPN 服务来访问`.

2021-04-28 08:44 UTC, zhyass commented on docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md
> +以下命令指定 release 名为 `demo`。
Refer to the suggestions above

2021-04-29 02:54 UTC, hustjieke commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +- [通过 Helm repo 部署 RadonDB MySQL 集群](#通过-Helm-repo-部署-RadonDB-MySQL-集群)
```
- [通过 Helm repo 部署 RadonDB MySQL 集群](#通过-Helm-repo-部署-RadonDB-MySQL-集群)
- [通过 Git 部署 RadonDB MySQL 集群](#通过-Git-部署-RadonDB-MySQL-集群)
- [通过控制台部署 RadonDB MySQL 集群](#通过控制台部署-RadonDB-MySQL-集群)
```
split to three files, like 
```
- [通过 Helm repo 部署 RadonDB MySQL 集群](link to filename1)
- [通过 Git 部署 RadonDB MySQL 集群](link to filename2)
- [通过控制台部署 RadonDB MySQL 集群](link to filename3)
```

2021-04-29 02:54 UTC, hustjieke commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +helm repo add <repo 名称> https://charts.kubesphere.io/test
do not use `<repo 名称>`,   change it to a real name   `test`

2021-04-29 04:05 UTC, runkecheng commented on docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
> +- [通过 Helm repo 部署 RadonDB MySQL 集群](#通过-Helm-repo-部署-RadonDB-MySQL-集群)
next pr

2021-04-29 05:43 UTC, hustjieke commented
LGTM

2021-04-29 08:18 UTC, closed without merging